# @package _group_
common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: roberta_mlm
  profile: True

distributed_training:
  ddp_backend: legacy_ddp

checkpoint:
  no_epoch_checkpoints: true

task:
  _name: masked_lm
  data: ???
  sample_break_mode: complete
  tokens_per_sample: 512

criterion: masked_lm

dataset:
  batch_size: 256
  ignore_unused_valid_subsets: true
  skip_invalid_size_inputs_valid_test: true

optimizer:
  _name: adam
  weight_decay: 0.01
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 10000

optimization:
  clip_norm: 0
  lr: [0.0005]
  max_update: 4000
  update_freq: [4]
  compute_threshold: 0.95

model:
  _name: roberta
  max_positions: 512
  dropout: 0.1
  attention_dropout: 0.1
